// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-header/CleanStrip.tsx": () => import("../components/mockups/dashboard-header/CleanStrip.tsx"),
  "./components/mockups/dashboard-header/CompactCards.tsx": () => import("../components/mockups/dashboard-header/CompactCards.tsx")
};
